name: Ruby Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: copy config file
      run: cp config/config.test.rb config/config.rb
    - name: Build docker-compose
      run: docker-compose build
    - name: Run unit tests
      run: docker-compose run --rm unit-test bundle exec rake test TESTOPTS='-v'
